name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build with Maven
      run: |
            cd /home/fomadmin/itoolsInterface
            mvn clean install
            
    - name: Set up Java and Maven
      uses: actions/setup-java@v2
      with:
        java-version: '20'
        maven-version: '3.4'  # Replace '3.x' with the desired Maven version
      
    - name: Set executable permissions for build.sh
      working-directory: jar
      run: chmod +x build.sh

    - name: Build JAR file
      run: |
        cd jar
        ./build.sh

    - name: Transfer JAR file to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "target/app.jar"
        target: "/home/fomadmin/itoolsInterface/target/app.jar"

    - name: Restart service
      run: sudo systemctl restart itoolsinterface.service
