name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set executable permissions for build.sh
        working-directory: jar
        run: chmod +x build.sh

      - name: Build and Deploy
        working-directory: jar
        run: bash build.sh

      - name: Transfer JAR file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "jar/app.jar"
          target: "/home/fomadmin/itoolsInterface/jar/app.jar"

      - name: Restart services
        run: sudo systemctl restart itoolsinterface.service
